rule all:
    input:
        basecall_log = "../ARS/ScriptResults/Script_Logs/basecall_log.txt",
        barcode_log = "../ARS/ScriptResults/Script_Logs/barcode_log.txt",
        count_reads_log = "../ARS/ScriptResults/Script_Logs/count_reads_log.txt",
        nanoqc_log = "../ARS/ScriptResults/Script_Logs/nanoqc_log.txt",
        guppy_aligner_log = "../ARS/ScriptResults/Script_Logs/guppy_aligner_log.txt",
        minimap_aligner_log = "../ARS/ScriptResults/Script_Logs/minimap_aligner_log.txt",
        data_frame_log = "../ARS/ScriptResults/Script_Logs/data_frame_log.txt",
        merge_files_log = "../ARS/ScriptResults/Script_Logs/merge_files_log.txt",
        plotly_log = "../ARS/ScriptResults/Script_Logs/plotly_logs.txt",
        nanoplot_log = "../ARS/ScriptResults/Script_Logs/nanoplot_logs.txt",
        trim_reads_log = "../ARS/ScriptResults/Script_Logs/trim_reads_log.txt"

rule count_reads:
    input:
        input_directory = "/home/joshl/minknow_data/demultiplex_dual",
        log_path = rules.all.input.count_reads_log
    output:
        save_directory = directory("/home/joshl/Desktop/temp/output/")
    script:
        "scripts/CountReads.py"
